### ISSUE TITLE
not working on statamic 4

### ISSUE THREAD

**Issue by trevmurray** [kadegray/statamic-phone-number-fieldtype#2] opened 2024-02-03 05:41 UTC
breaks the control panel; the control panel freezes when installed. In particular, the create field screen spins and never opens when attempting to add a field to a fieldset.

/cp/fields/fieldtypes?selectable=true:1 
        
`Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

**Comment by kadegray** [comment] 2024-02-03 06:38
Hi @trevmurray, if you could please provide the php error I should then be able to investigate further. Thanks

**Comment by kadegray** [comment] 2024-03-14 08:26
Hi @trevmurray, I've been unable to produce a 500 error in Statamic 4. Do you have any more information on this issue?

**Comment by kadegray** [comment] 2024-03-25 07:41
I'm going to close this issue since theres not enough information provided to reproduce. @trevmurray please feel free to create another issue if it happens again. Please provide the PHP error.

**Closed as not planned by kadegray** 2024-03-25 07:41 UTC
